---
title: felangga
timezone: Asia/Jakarta
collections:
  posts:
    title: Posts
    output: true
  tabs:
    title: Tabs
    output: true
    sort_by: order
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    toc: true
    permalink: "/posts/:title/"
- scope:
    path: _drafts
  values:
    comments: false
- scope:
    path: ''
    type: tabs
  values:
    layout: page
    permalink: "/:title/"
- scope:
    path: assets/img/favicons
  values:
    swcache: true
- scope:
    path: assets/js/dist
  values:
    swcache: true
theme: jekyll-theme-chirpy
plugins:
- jekyll-archives
- jekyll-paginate
- jekyll-sitemap
- jekyll-seo-tag
baseurl: ''
lang: en
tagline: personal blog
description: 'hobbies and interesting sttufs '
url: https://felangga.github.io
github:
  username: felangga
twitter:
  username: erlandhita
social:
  name: felangga
  email: felangga@gmail.com
  links:
  - https://twitter.com/erlandhita
  - https://github.com/felangga
google_site_verification: 
google_analytics:
  id: 
  pv:
    proxy_endpoint: 
    cache_path: 
theme_mode: dark
img_cdn: 
avatar: https://avatars.githubusercontent.com/u/14814984?s=400&v=4
toc: true
comments:
  active: giscus
  disqus:
    shortname: 
  utterances:
    repo: 
    issue_term: 
  giscus:
    repo: felangga/felangga.github.io
    repo_id: R_kgDOJbiJUQ
    category: Q&A
    category_id: DIC_kwDOJbiJUc4CWxmt
    mapping: pathname
    input_position: 
    lang: 
    reactions_enabled: 
assets:
  self_host:
    enabled: 
    env: 
pwa:
  enabled: true
paginate: 10
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs:
    - development
exclude:
- "*.gem"
- "*.gemspec"
- tools
- README.md
- CHANGELOG.md
- LICENSE
- rollup.config.js
- node_modules
- package*.json
jekyll-archives:
  enabled:
  - categories
  - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: "/tags/:name/"
    category: "/categories/:name/"
